### ISSUE TITLE
mod fails to load

### ISSUE THREAD

**Issue by the-wildguy** [firef1a/HyperViewer#1]
error: <html>Mod 'HyperViewer' (hyperviewer) 1.0.0 requires version 21 or later of 'OpenJDK 64-Bit Server VM' (java), but only the<br>wrong version is present: 17!</html>

I tried installing java 21, doesn't work

mc version 1.20.4
fabric version 0.16.5

**Comment by miawara** [comment]
are you using the default minecraft launcher or something else like multimc etc?

**Comment by the-wildguy** [comment]
The default launcher through curseforge, I'll check if there's a curseforge setting to change the java version

**Comment by miawara** [comment]
The issue was that I set the java version compatibility too high, I'll release a new version with that fixed.

**Comment by the-wildguy** [comment]
this [video](https://youtu.be/EGUsEq6HOd0?si=bKhK1y-qmofmtS6z&t=58) is a good enough fix in the meantime, you have to redo the steps everytime you load the launcher though.

by the way the default version is 17
